"""changed pitches schemas

Revision ID: 4c4735eaab58
Revises: 55ff9f29cdd8
Create Date: 2022-05-11 01:31:07.429325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4735eaab58'
down_revision = '55ff9f29cdd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'title')
    # ### end Alembic commands ###
