"""changed pitches schema

Revision ID: 55ff9f29cdd8
Revises: d2f67d3843ff
Create Date: 2022-05-11 01:11:25.179089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ff9f29cdd8'
down_revision = 'd2f67d3843ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('pitches', sa.Column('author', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('category', sa.Integer(), nullable=True))
    op.drop_constraint('pitches_category_id_fkey', 'pitches', type_='foreignkey')
    op.drop_constraint('pitches_user_id_fkey', 'pitches', type_='foreignkey')
    op.create_foreign_key(None, 'pitches', 'categories', ['category'], ['name'])
    op.create_foreign_key(None, 'pitches', 'users', ['author'], ['username'])
    op.drop_column('pitches', 'category_id')
    op.drop_column('pitches', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.create_foreign_key('pitches_user_id_fkey', 'pitches', 'users', ['user_id'], ['id'])
    op.create_foreign_key('pitches_category_id_fkey', 'pitches', 'categories', ['category_id'], ['id'])
    op.drop_column('pitches', 'category')
    op.drop_column('pitches', 'author')
    op.drop_column('categories', 'title')
    # ### end Alembic commands ###
