"""changed categories schemas

Revision ID: 7237eace1cc4
Revises: 4b1d514bc583
Create Date: 2022-05-11 01:34:43.915548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7237eace1cc4'
down_revision = '4b1d514bc583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.add_column('pitches', sa.Column('category_name', sa.Integer(), nullable=True))
    op.drop_constraint('pitches_category_id_fkey', 'pitches', type_='foreignkey')
    op.create_foreign_key(None, 'pitches', 'categories', ['category_name'], ['name'])
    op.drop_column('pitches', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.create_foreign_key('pitches_category_id_fkey', 'pitches', 'categories', ['category_id'], ['id'])
    op.drop_column('pitches', 'category_name')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    # ### end Alembic commands ###
