"""changed categories schemas

Revision ID: ac4433502026
Revises: 0ea980b97aeb
Create Date: 2022-05-11 01:37:41.803047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4433502026'
down_revision = '0ea980b97aeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.add_column('pitches', sa.Column('category_name', sa.Integer(), nullable=True))
    op.drop_constraint('pitches_category_id_fkey', 'pitches', type_='foreignkey')
    op.create_foreign_key(None, 'pitches', 'categories', ['category_name'], ['id'])
    op.drop_column('pitches', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.create_foreign_key('pitches_category_id_fkey', 'pitches', 'categories', ['category_id'], ['id'])
    op.drop_column('pitches', 'category_name')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    # ### end Alembic commands ###
